In [151]:
import pandas as pd

In [152]:
path = "/Users/sel/Desktop/python_projects/student_mental_health/Student Mental health.csv"

In [153]:
df = pd.read_csv(path)

In [154]:
df.shape

(101, 11)

In [155]:
df.columns

Index(['Timestamp', 'Choose your gender', 'Age', 'What is your course?',
       'Your current year of Study', 'What is your CGPA?', 'Marital status',
       'Do you have Depression?', 'Do you have Anxiety?',
       'Do you have Panic attack?',
       'Did you seek any specialist for a treatment?'],
      dtype='str')

In [156]:
df.dtypes

Timestamp                                           str
Choose your gender                                  str
Age                                             float64
What is your course?                                str
Your current year of Study                          str
What is your CGPA?                                  str
Marital status                                      str
Do you have Depression?                             str
Do you have Anxiety?                                str
Do you have Panic attack?                           str
Did you seek any specialist for a treatment?        str
dtype: object

In [157]:
df.isna().sum()

Timestamp                                       0
Choose your gender                              0
Age                                             1
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              0
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
dtype: int64

In [158]:
df[df["Age"].isna()]

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
43,04/24/2022 07:19:59,Male,NaN,BIT,year 1,0 - 1.99,No,No,No,No,No

In [159]:
df["Your current year of Study"]

0      year 1
1      year 2
2      Year 1
3      year 3
4      year 4
        ...
96     year 1
97     Year 2
98     Year 3
99     year 4
100    Year 2
Name: Your current year of Study, Length: 101, dtype: str

In [86]:
df["Your current year of Study"].str.lower()

0      year 1
1      year 2
2      year 1
3      year 3
4      year 4
        ...
96     year 1
97     year 2
98     year 3
99     year 4
100    year 2
Name: Your current year of Study, Length: 101, dtype: str

In [160]:
df["Your current year of Study"] = df["Your current year of Study"].str.lower()

In [161]:
df["Your current year of Study"]

0      year 1
1      year 2
2      year 1
3      year 3
4      year 4
        ...
96     year 1
97     year 2
98     year 3
99     year 4
100    year 2
Name: Your current year of Study, Length: 101, dtype: str

In [89]:
df["What is your CGPA?"].unique()

<StringArray>
[ '3.00 - 3.49',  '3.50 - 4.00', '3.50 - 4.00 ',  '2.50 - 2.99',
  '2.00 - 2.49',     '0 - 1.99']
Length: 6, dtype: str

In [90]:
df["What is your CGPA?"] = df["What is your CGPA?"].str.strip()

In [91]:
df["What is your CGPA?"].unique()

<StringArray>
['3.00 - 3.49', '3.50 - 4.00', '2.50 - 2.99', '2.00 - 2.49', '0 - 1.99']
Length: 5, dtype: str

In [92]:
df[df["Do you have Anxiety?"] == "Yes"].shape[0]

34

In [93]:
df[df["Do you have Anxiety?"] == "Yes"]["Do you have Anxiety?"].count()

np.int64(34)

In [94]:
df.shape

(101, 11)

In [95]:
df.shape[0]

101

In [96]:
df.shape[1]

11

In [97]:
df[df["Do you have Depression?"] == "Yes"].shape[0]

35

In [98]:
df[(df["Do you have Depression?"] == "Yes") & (df["Do you have Anxiety?"] == "Yes")].shape[0]

18

In [99]:
df.groupby("Do you have Anxiety?")[["What is your CGPA?", "Did you seek any specialist for a treatment?"]].value_counts()

Do you have Anxiety?  What is your CGPA?  Did you seek any specialist for a treatment?
No                    3.50 - 4.00         No                                              29
                      3.00 - 3.49         No                                              28
                      0 - 1.99            No                                               4
                      2.00 - 2.49         No                                               2
                      2.50 - 2.99         Yes                                              2
                                          No                                               1
                      3.50 - 4.00         Yes                                              1
Yes                   3.00 - 3.49         No                                              15
                      3.50 - 4.00         No                                              15
                                          Yes                                              3
                      2.50 - 2.99         No                                               1
Name: count, dtype: int64

In [100]:
df.groupby("Do you have Depression?")[["What is your CGPA?", "Did you seek any specialist for a treatment?"]].value_counts()

Do you have Depression?  What is your CGPA?  Did you seek any specialist for a treatment?
No                       3.50 - 4.00         No                                              35
                         3.00 - 3.49         No                                              24
                         0 - 1.99            No                                               4
                         2.00 - 2.49         No                                               2
                         2.50 - 2.99         No                                               1
Yes                      3.00 - 3.49         No                                              19
                         3.50 - 4.00         No                                               9
                                             Yes                                              4
                         2.50 - 2.99         Yes                                              2
                                             No                                               1
Name: count, dtype: int64

In [101]:
df[["Do you have Anxiety?", "Do you have Depression?"]].value_counts(normalize=True)

Do you have Anxiety?  Do you have Depression?
No                    No                         0.495050
Yes                   Yes                        0.178218
No                    Yes                        0.168317
Yes                   No                         0.158416
Name: proportion, dtype: float64

In [103]:
df["Do you have Anxiety?"].value_counts()

Do you have Anxiety?
No     67
Yes    34
Name: count, dtype: int64

In [104]:
df.groupby("Do you have Depression?")["Do you have Anxiety?"].value_counts(normalize=True)

Do you have Depression?  Do you have Anxiety?
No                       No                      0.757576
                         Yes                     0.242424
Yes                      Yes                     0.514286
                         No                      0.485714
Name: proportion, dtype: float64

In [105]:
df[df["Age"].between(18, 21)]

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,05/27/2021 05:40:50,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,05/20/2021 09:18:10,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,05/21/2023 13:27:43,Male,19.0,BIT,year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
5,02/02/2023 16:35:50,Male,19.0,Engineering,year 2,3.50 - 4.00,No,No,No,Yes,No
7,03/08/2024 03:13:12,Female,18.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...
95,06/27/2024 16:15:34,Female,18.0,Islamic Education,year 1,3.50 - 4.00,No,No,No,No,No
96,05/23/2021 19:19:27,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,07/11/2025 12:09:57,Male,18.0,Engineering,year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,07/13/2025 09:46:05,Female,19.0,Nursing,year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
100,11/28/2022 20:21:15,Male,20.0,Biomedical science,year 2,3.00 - 3.49,No,No,No,No,No

In [107]:
df.to_csv("student_mental_health_cleaned.csv", index=False)

In [108]:
df.groupby("Do you have Depression?")["Choose your gender"].value_counts()

Do you have Depression?  Choose your gender
No                       Female                46
                         Male                  20
Yes                      Female                29
                         Male                   6
Name: count, dtype: int64

In [126]:
df.groupby("Do you have Depression?")["Age"].describe()

,count,mean,std,min,25%,50%,75%,max
Do you have Depression?,,,,,,,,
No,65.0,20.661538,2.557324,18.0,18.0,19.0,24.0,24.0
Yes,35.0,20.285714,2.395724,18.0,18.0,19.0,23.0,24.0

In [134]:
df["Age"].describe()

count    100.00000
mean      20.53000
std        2.49628
min       18.00000
25%       18.00000
50%       19.00000
75%       23.00000
max       24.00000
Name: Age, dtype: float64

In [127]:
df.groupby("Do you have Depression?")["Your current year of Study"].value_counts()

Do you have Depression?  Your current year of Study
No                       year 1                        29
                         year 2                        16
                         year 3                        14
                         year 4                         7
Yes                      year 1                        14
                         year 3                        10
                         year 2                        10
                         year 4                         1
Name: count, dtype: int64

In [128]:
df.groupby("Do you have Depression?")["What is your CGPA?"].value_counts()

Do you have Depression?  What is your CGPA?
No                       3.50 - 4.00           35
                         3.00 - 3.49           24
                         0 - 1.99               4
                         2.00 - 2.49            2
                         2.50 - 2.99            1
Yes                      3.00 - 3.49           19
                         3.50 - 4.00           13
                         2.50 - 2.99            3
Name: count, dtype: int64

In [129]:
df.groupby("Do you have Depression?")["Do you have Anxiety?"].value_counts()

Do you have Depression?  Do you have Anxiety?
No                       No                      50
                         Yes                     16
Yes                      Yes                     18
                         No                      17
Name: count, dtype: int64

In [130]:
df.groupby("Do you have Depression?")["Did you seek any specialist for a treatment?"].value_counts()

Do you have Depression?  Did you seek any specialist for a treatment?
No                       No                                              66
Yes                      No                                              29
                         Yes                                              6
Name: count, dtype: int64

In [138]:
df.groupby("Do you have Anxiety?")["Choose your gender"].value_counts(normalize=True)

Do you have Anxiety?  Choose your gender
No                    Female                0.761194
                      Male                  0.238806
Yes                   Female                0.705882
                      Male                  0.294118
Name: proportion, dtype: float64

In [132]:
df.groupby("Do you have Anxiety?")["Age"].describe()

                      count       mean      std   min   25%   50%   75%   max
Do you have Anxiety?
No                     66.0  20.696970  2.49288  18.0  18.0  19.0  23.0  24.0
Yes                    34.0  20.205882  2.50792  18.0  18.0  19.0  23.0  24.0

In [139]:
df.groupby("Do you have Anxiety?")["Your current year of Study"].value_counts(normalize=True)

Do you have Anxiety?  Your current year of Study
No                    year 1                        0.432836
                      year 3                        0.238806
                      year 2                        0.238806
                      year 4                        0.089552
Yes                   year 1                        0.411765
                      year 2                        0.294118
                      year 3                        0.235294
                      year 4                        0.058824
Name: proportion, dtype: float64

In [140]:
df.groupby("Do you have Anxiety?")["Did you seek any specialist for a treatment?"].value_counts(normalize=True)

Do you have Anxiety?  Did you seek any specialist for a treatment?
No                    No                                              0.955224
                      Yes                                             0.044776
Yes                   No                                              0.911765
                      Yes                                             0.088235
Name: proportion, dtype: float64